### ISSUE TITLE
@Arduino Program

### ISSUE THREAD

**Issue by farhannaseh** [flarets/syringe_pump#1]
Hi ...
Please help in following issues:
1) For program to run, does it require any specific LCDKeypad/TimerOne library or any library available online can be used? Please provide with library links then.
2) Can the program be used for smaller syringes < 5ml and flow rates~few microlitres per min?
3) In **"unsigned int NSTEPS = 10;"** , what is NSTEPS?
4) In **float flow_rate_increment = 1/60.0; // flow rate increment, mL/s**, units ml/s or ml/min?
5)Please explain this **delay_per_step = 0.8e6/(revs_per_s * steps_per_revolution * usteps_per_step[USTEPS_INDEX]);** , I was unable to figure out why 0.8e6?
Please reply asap.

**Comment by flarets** [comment]
1. Libraries are:
http://playground.arduino.cc/Code/Timer1
https://github.com/barnybug/arduino-sous-vide/tree/master/libraries/LCDKeypad
2. Smaller syringes should be fine, just get your constants right. You can go as slow as you like.
3. NSTEPS was just to make the minimum volume increment a practical size I think, if you need finer resolution you can reduce it. 
4. mL/s
5. The 1e6 is because it's microsteps. From testing I found a factor of 0.8 was necessary for the speed to be right. Really not sure why it was necessary.

**Comment by farhannaseh** [comment]
Hey, thanx for the immediate response.
I am using a 3ml syringe and trying for flow rates < 0.1 ml/h (1.667 ul/min).

1. Can you help in which values to change for obtaining flow rate of **1ul/min** as example. I had tried 
   myself though keeping NSTEPS=10 only. By what factor or relation should NSTEPS be reduced?
2. What is the min and max limit for flow rates that can be achieved?
3. Can you tell me how can I input values for "Syringe barrel length" and "Syringe volume" via LCD buttons 
   instead of defining in the program so that different syringes say 1ml,2ml,3ml,5ml can be used without 
   always modifying the program or just standardize some length and volume values in program once and 
   call or select by scrolling through LCD buttons.   
4. For 0.8e6, you said you did some testing. How was it done can you tell?

Waiting for your help ... Do reply soon  ...

**Comment by farhannaseh** [comment]
Hey, thanx for the immediate response.
I am using a 3ml syringe and trying for flow rates < 0.1 ml/h (1.667 ul/min).

1. Can you help in which values to change for obtaining flow rate of 1ul/min as example. I had tried
   myself though keeping NSTEPS=10 only. By what factor or relation should NSTEPS be reduced?
   What is the min and max limit for flow rates that can be achieved?
2. Can you tell me how can I input values for "Syringe barrel length" and "Syringe volume" via LCD 
   buttons instead of defining in the program so that different syringes say 1ml,2ml,3ml,5ml can be used 
   without always modifying the program or just standardize some length and volume values in program 
   once and call or select by scrolling through LCD buttons.
3. For 0.8e6, you said you did some testing. How was it done can you tell?

Waiting for your help ... Do reply soon ...
